// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPWxODWOYGJPpf5Ar09FCY7X2lWkN8WeM',
    appId: '1:995545944430:web:2d9642c9669e72666c717f',
    messagingSenderId: '995545944430',
    projectId: 'cotaskhub',
    authDomain: 'cotaskhub.firebaseapp.com',
    storageBucket: 'cotaskhub.appspot.com',
    measurementId: 'G-CB2QYTE58V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbQ2x_FrkLwW3lGKt9XLV4gYXZkZNKvww',
    appId: '1:995545944430:android:2c10ea012c0c90166c717f',
    messagingSenderId: '995545944430',
    projectId: 'cotaskhub',
    storageBucket: 'cotaskhub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-3kQUwa4VdpfWys1tCtulpNmXzvCVqzU',
    appId: '1:995545944430:ios:7a4e0ec0923512136c717f',
    messagingSenderId: '995545944430',
    projectId: 'cotaskhub',
    storageBucket: 'cotaskhub.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-3kQUwa4VdpfWys1tCtulpNmXzvCVqzU',
    appId: '1:995545944430:ios:d2de453ea82308da6c717f',
    messagingSenderId: '995545944430',
    projectId: 'cotaskhub',
    storageBucket: 'cotaskhub.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
